name: totter
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6
  - selenium
  - pip:
    - pyqt5==5.11.3
    - pyqt5-sip==4.19.13
    - pywebview==2.1
    - pyobjc-core
    - pyobjc
    - pyautogui
    - pytesseract
